// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "megalodon":return img`
.............ccfff..............
...........ccddbcf..............
..........ccddbbf...............
..........fccbbcf...............
.....fffffccccccff.........ccc..
...ffbbbbbbbcbbbbcfff....ccbbc..
..fbbbbbbbbcbcbbbbcccff.cdbbc...
ffbbbbbbffbbcbcbbbcccccfcdbbf...
fbcbbb11ff1bcbbbbbcccccffbbf....
fbbb11111111bbbbbcccccccbbcf....
.fb11133cc11bbbbcccccccccccf....
..fccc31c111bbbcccccbdbffbbcf...
...fc13c111cbbbfcddddcc..fbbf...
....fccc111fbdbbccdcc.....fbbf..
........ccccfcdbbcc........fff..
.............fffff..............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
